version: '3.8'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_floweradvisor
      MYSQL_USER: user_floweradvisor
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"