name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sync Files to Docker Container
        run: |
          tar -czf - . | ssh -i ~/.ssh/id_rsa administrator@192.168.0.111 "
          docker exec -i floweradvisor sh -c 'tar -xzf - -C /var/www/html'"

      - name: Reload Application in Docker
        run: |
          ssh -i ~/.ssh/id_rsa administrator@192.168.0.111 "docker exec -i floweradvisor sh -c 'touch tmp/restart.txt'"